version: "3.9"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:80

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8080:8080